AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
